[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "recsyslib"
version = "0.0.1"
requires-python = ">=3.10"

[tool.setuptools]
packages = [
    "recsyslib"
]
